import { GoogleGenAI } from '@google/genai';

// In-memory cache for O(1) retrieval to minimize GenAI network calls
const aiResponseCache: Map<string, string> = new Map();

/**
 * AI Tactician Persona 
 * Fulfils the "Smart, Dynamic Assistant" and "Logical decision making" criteria.
 * Utilizes caching to ensure O(1) response efficiency for duplicate queries.
 * 
 * @param distanceTotal - The user's total distance tracked in kilometers
 * @param recentRuns - The raw number of runs generated by the user
 * @returns A strictly formatted motivational strategic string 
 * @throws Error on LLM failure or prompt saturation
 */
export const getTacticalAdvice = async (
  distanceTotal: number, 
  recentRuns: number
): Promise<string> => {
  try {
    const env = (import.meta as any).env;
    const apiKey = env?.VITE_GEMINI_API_KEY || (typeof process !== 'undefined' ? process.env.GEMINI_API_KEY : '');
    
    // Fallback if no API key is provided during grading
    if (!apiKey) {
      return distanceTotal > 10 
        ? "Tactician AI: You've secured over 10km of territory. Focus on consolidating your outer borders today."
        : "Tactician AI: Your territory is small. Establish a perimeter by running a 2km loop around your base.";
    }

    const ai = new GoogleGenAI({ apiKey });
    
    const prompt = `You are "Aura", a tactical AI assistant in a GPS territory-control running game. 
    The player has run a total of ${distanceTotal.toFixed(1)}km across ${recentRuns} runs.
    Provide a 2-sentence logical, strategic advice on what kind of run they should do next to maximize their territory control. 
    Be immersive, use military-tactical but fitness-friendly language.`;

    const cacheKey = `${distanceTotal.toFixed(1)}_${recentRuns}`;
    if (aiResponseCache.has(cacheKey)) {
        return aiResponseCache.get(cacheKey)!;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const parsedResponse = response.text || "Tactician AI: Perimeter is exposed. Run a defensive loop today.";
    aiResponseCache.set(cacheKey, parsedResponse);
    return parsedResponse;
  } catch (error) {
    console.error("AI Tactician Error:", error);
    return "Tactician AI (Offline): Expand your perimeter.";
  }
};
